<a href="https://colab.research.google.com/github/hareeshkhs/Numpy-Tutorial/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Welcome to numpy part 2
# slicing/stacking arrays, indexing with boolean arrays

Importing numpy Module as np

In [9]:
import numpy as np

In [10]:
#To create an numpy array using list
arr1=np.array([1, 2, 3])
print(arr1)
#To create a multi-dimensional array
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr2)
# 3X3 multi-dimensional array
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[1 2 3]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Slicing in the Array**

Slicing in the NumPy array is the way to extract a range of elements from an array. Slicing in the array is performed in the same way as it is performed in the python list.

Consider the following examples

In [11]:
print(arr1[0:2])
print(arr1[-1])
print(arr2[0,1])
print(arr2[2,0])
#printing element from 2nd row 3rd col
print(arr3[1,2])
print(arr3[0:2,2])
print(arr3[-1])

[1 2]
3
2
5
6
[3 6]
[7 8 9]


**NumPy Array Iteration**

NumPy provides an iterator object, i.e., nditer which can be used to iterate over the given array using python standard Iterator interface.

Consider the following examples.

In [14]:
for row in arr3:
  print(row)
print("*************")
for a in arr3.flat:
  print(a)

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


In [15]:
a1=np.arange(6).reshape(3,2)
a2=np.arange(6,12).reshape(3,2)
print(a1)
print(a2)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


**Array Concatenation**

The numpy provides us with the vertical stacking and horizontal stacking which allows us to concatenate two multi-dimensional arrays vertically or horizontally.

Consider the following example.

In [18]:
print("Arrays vertically concatenated\n",np.vstack((a1,a2))) 
print("Arrays horizontally concatenated\n",np.hstack((a1,a2)))

Arrays vertically concatenated
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Arrays horizontally concatenated
 [[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [19]:
a3=np.arange(30).reshape(2,15)
print(a3)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [21]:
result = np.hsplit(a3,3)
print(result[0])
print(result[1])
print(result[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [24]:
result1 = np.vsplit(a3,2)
print(result1[0])
print(result1[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [27]:
a4=np.arange(12).reshape(3,4)
print(a4)
print("*************")
b = a4 > 5
print(b)
print("*************")
print(a4[b])
print("*************")
a4[b]=-1
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
*************
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
*************
[ 6  7  8  9 10 11]
*************
[[ 0  1  2  3]
 [ 4  5 -1 -1]
 [-1 -1 -1 -1]]
