<a href="https://colab.research.google.com/github/hareeshkhs/Numpy-Tutorial/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Introduction with Basic array operations:
**Numpy Setup:**
NumPy doesn't come bundled with Python. We have to install it using the python pip installer. Execute the following command.

`$ pip install numpy`

Importing numpy Module as np

In [2]:
import numpy as np

**NumPy Ndarray:**
Ndarray is the n-dimensional array object defined in the numpy which stores the collection of the similar type of elements. In other words, we can define a ndarray as the collection of the data type (dtype) objects.

The ndarray object can be created by using the array routine of the numpy module.

The syntax:

`numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)`  
Example:

In [3]:
np.array

<function numpy.array>

In [4]:
#To create an numpy array using list
arr1=np.array([1, 2, 3])
print(arr1)
#To create a multi-dimensional array
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr2)

[1 2 3]
[[1 2]
 [3 4]
 [5 6]]


To change the data type of the array elements, mention the name of the data type along with the collection.

In [5]:
arr3=np.array([1, 2, 3], dtype=float)
print(arr3)
arr3=np.array([1, 2, 3, 4], dtype=complex)
print(arr3)

[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


**Finding the dimensions of the Array**

The ndim function can be used to find the dimensions of the array.

In [6]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
1


**Finding the size of each array element**

The itemsize function is used to get the size of each array item. It returns the number of bytes taken by each array element.

Consider the following example.

In [7]:
print("Each item contains in arr1:",arr1.itemsize)
print("Each item contains in arr3:",arr3.itemsize)

Each item contains in arr1: 8
Each item contains in arr3: 16


**Finding the data type of each array item**

To check the data type of each array item, the dtype function is used. Consider the following example to check the data type of the array items.

In [8]:
print("Each item is of the type in arr1:",arr1.dtype)
print("Each item is of the type in arr3:",arr3.dtype)

Each item is of the type in arr1: int64
Each item is of the type in arr3: complex128


**Finding the shape and size of the array**

To get the shape and size of the array, the size and shape function associated with the numpy array is used.

In [9]:
#arr1=np.array([1, 2, 3])
#arr2=np.array([[1,2],[3,4],[4,5]])

print("Array Size of arr1:",arr1.size)  
print("Shape of arr1:",arr1.shape)

print("Array Size of arr2:",arr2.size)  
print("Shape of arr2:",arr2.shape)

Array Size of arr1: 3
Shape of arr1: (3,)
Array Size of arr2: 6
Shape of arr2: (3, 2)


**NumPy.Zeros**

This routine is used to create the numpy array with the specified shape where each numpy array item is initialized to 0.

The syntax is given below.

`numpy.zeros(shape, dtype = float, order = 'C') `

It accepts the following parameters.

Shape: The desired shape of the specified array.

dtype: The data type of the array items. The default is the float.

Order: The default order is the c-style row-major order. It can be set to F for FORTRAN-style column-major order.

In [10]:
arrofzeros = np.zeros((3,2), dtype = int)  
print(arrofzeros)

[[0 0]
 [0 0]
 [0 0]]


**NumPy.ones**

This routine is used to create the numpy array with the specified shape where each numpy array item is initialized to 1.

The syntax to use this module is given below.

`numpy.ones(shape, dtype = none, order = 'C')`

In [11]:
arrofones = np.ones((3,3), dtype = float)  
print(arrofones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Numpy.arrange**

It creates an array by using the evenly spaced values over the given interval. The syntax to use the function is given below.

`numpy.arrange(start, stop, step, dtype) `

It accepts the following parameters.

start: The starting of an interval. The default is 0.

stop: represents the value at which the interval ends excluding this value.

step: The number by which the interval values change.

dtype: the data type of the numpy array items.

In [12]:
a1 = np.arange(0,10)  
print(a1)
a2 = np.arange(1,10,3,float)  
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[1. 4. 7.]


**NumPy.linspace**

It is similar to the arrange function. However, it doesn?t allow us to specify the step size in the syntax.

Instead of that, it only returns evenly separated values over a specified period. The system implicitly calculates the step size.

The syntax is given below.

`numpy.linspace(start, stop, num, endpoint, retstep, dtype)` 

In [13]:
a3 = np.linspace(10, 20, 5)  
print("The array over the given range is ",a3)

a4 = np.linspace(10, 20, 5, endpoint = False)  
print("The array over the given range is ",a4)

The array over the given range is  [10.  12.5 15.  17.5 20. ]
The array over the given range is  [10. 12. 14. 16. 18.]


**Reshaping the array objects**

By the shape of the array, we mean the number of rows and columns of a multi-dimensional array. However, the numpy module provides us the way to reshape the array by changing the number of rows and columns of the multi-dimensional array.

The reshape() function associated with the ndarray object is used to reshape the array. It accepts the two parameters indicating the row and columns of the new shape of the array.

Let's reshape the array of shape(3X2).


In [16]:
print(arr2)  
a5 = arr2.reshape(2,3)  
print("printing the reshaped array(3X2)")  
print(a5)

a6 = arr2.reshape(6,1)
print("printing the reshaped array(6X1)")
print(a6)

[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array(3X2)
[[1 2 3]
 [4 5 6]]
printing the reshaped array(6X1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


**numpy.ravel()**

Syntax:

`numpy.ravel(x, order='C')`

This function returns a contiguous flatten array with the same data type as an input array and has shape equal to (x.size).

In [17]:
x = np.array([[1, 3, 5], [7, 9, 11]])  
y=np.ravel(x)  
print(y)

[ 1  3  5  7  9 11]


**Finding the maximum, minimum, and sum of the array elements**

The NumPy provides the max(), min(), and sum() functions which are used to find the maximum, minimum, and sum of the array elements respectively.

Consider the following example.

In [20]:
a7 = np.array([[1,2,3],[10,15,4]])  
print("The array:\n",a7)  
print("The maximum element:",a7.max())  
print("The minimum element:",a7.min())  
print("The sum of the elements:",a7.sum())

The array:
 [[ 1  2  3]
 [10 15  4]]
The maximum element: 15
The minimum element: 1
The sum of the elements: 35


**NumPy Array Axis**

A NumPy multi-dimensional array is represented by the axis where axis-0 represents the columns and axis-1 represents the rows. We can mention the axis to perform row-level or column-level calculations like the addition of row or column elements.

numpy-array-axis.png

To calculate the maximum element among each column, the minimum element among each row, and the addition of all the row elements, consider the following example.

In [22]:
#a7 = np.array([[1,2,3],[10,15,4]])

print("The array:\n",a7)
print("The maximum elements of columns:",a7.max(axis = 0))   
print("The minimum element of rows",a7.min(axis = 1))  
print("The sum of all rows",a7.sum(axis = 1))

The array:
 [[ 1  2  3]
 [10 15  4]]
The maximum elements of columns: [10 15  4]
The minimum element of rows [1 4]
The sum of all rows [ 6 29]


**Finding square root and standard deviation**

The sqrt() and std() functions associated with the numpy array are used to find the square root and standard deviation of the array elements respectively.

Standard deviation means how much each element of the array varies from the mean value of the numpy array.

Consider the following example.

In [24]:
#a7 = np.array([[1,2,3],[10,15,4]])

print(np.sqrt(a7))
print("*********************") 
print(np.std(a7))

[[1.         1.41421356 1.73205081]
 [3.16227766 3.87298335 2.        ]]
*********************
5.013869652163774


**Arithmetic operations on the array**

The numpy module allows us to perform the arithmetic operations on multi-dimensional arrays directly.

In the following example, the arithmetic operations are performed on the two multi-dimensional arrays a and b.

In [25]:
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print("Sum of array a and b\n",a+b)  
print("Product of array a and b\n",a*b)  
print("Division of array a and b\n",a/b)  

Sum of array a and b
 [[ 2  4 33]
 [22 34 33]]
Product of array a and b
 [[  1   4  90]
 [120 285 116]]
Division of array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


**NumPy Matrix Multiplication in Python**

Multiplication of matrix is an operation which produces a single matrix by taking two matrices as input and multiplying rows of the first matrix to the column of the second matrix. Note that we have to ensure that the number of rows in the first matrix should be equal to the number of columns in the second matrix.

**Dot product**


In [26]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)  
array2=np.array([[9,8,7],[6,5,4],[3,2,1]],ndmin=3)  
result=np.dot(array1,array2)  
print(result)

[[[[ 30  24  18]]

  [[ 84  69  54]]

  [[138 114  90]]]]
